### ISSUE TITLE
update torch version

### ISSUE THREAD

**Issue by antonkulaga** [ml-jku/DeepRC#3]
At the moment the library uses old torch version that forces the user to use python 3.7, it will be nice to update to a newer one. I would also consider publishing for conda.

**Comment by widmi** [comment]
added support for compatibility with different h5py versions (ef3675fb1596a555dd015c0ac8bb2eb4fd324967), which seems to have been the main issue with newer python versions.
did not test all functionalities but got feedback from other labs that successfully run the repo using other python and pytorch versions.
