### ISSUE TITLE
Datasets issue (?)

### ISSUE THREAD

**Issue by MathiasHilfiker** [ml-jku/DeepRC#6]
I'm trying to run the examples as in README, but I continue getting the error:

KeyError: "Samples ['' '' '' ... '' '' ''] could not be found in hdf5 file. Please add the samples and re-create the hdf5 file or remove the sample keys from the used samples of the metadata file."

This happens with all the datasets I tried in the "Training DeepRC on pre-defined datasets" section. Instead, when I try running the code in the "Training DeepRC on a custom dataset" section, on the example dataset deeprc/datasets/example_dataset, I get:

ValueError: not enough values to unpack (expected 6, got 0)

The versions of the libraries I'm using are the same as yours, what am I missing?

**Comment by ndalchau** [comment]
Me too. Did you find a solution yourself?

**Comment by MathiasHilfiker** [comment]
I solved the first problem by installing the older version (261d2b6).
Instead, for the second error, I haven't still found a solution

**Comment by widmi** [comment]
Hi! Thanks for the notice!

Regarding `KeyError: "Samples ['' '' '' ... '' '' ''] could not be found in hdf5 file`: As advised via email, please use the older version for now. Either the latest [release v.0.0.5](https://github.com/ml-jku/DeepRC/tree/v0.0.5) or the corresponding commit https://github.com/ml-jku/DeepRC/commit/261d2b65249933f7197406dbe3f59f4a5e4f9089 should work. I will fix this in a new release as soon as I have time but it might take a bit. You can install the release version using `pip3 install --no-dependencies https://github.com/ml-jku/DeepRC/archive/refs/tags/v0.0.5.tar.gz` or `pip3 install https://github.com/ml-jku/DeepRC/archive/refs/tags/v0.0.5.tar.gz`.

Regarding the second error: Is this the `ValueError`? Could you please open a separate issue with a more detailed description of the program output/error message @MathiasHilfiker ? It seems to be not related to the KeyError, if I understood correctly?
